/**
 * The open drafts, as git remembers them.
 *
 * GENERATED by `node scripts/drafts.mjs` — do not edit. The author's words in
 * here (a revision's note, its section states) come from the frontmatter of the
 * commit that saved it; everything else is computed.
 *
 * Plain `.js` for the same reason as `glossary.data.js`: the types live next
 * door in `drafts.ts`, which re-exports this, and JSDoc keeps checking.
 *
 * @type {import('./drafts').Drafts}
 */
export const DRAFTS = {
	"003-pure-joy-vi": {
		"edits": 11,
		"startedAt": "2026-08-17",
		"promise": "không hứa",
		"current": "r11",
		"revisions": [
			{
				"r": "r01",
				"n": 1,
				"date": "2026-08-16T19:49:27+07:00",
				"words": 139,
				"note": "mới chỉ có cái thí nghiệm. chưa biết mình muốn nói gì về nó.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "editing"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "notes"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "notes"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem đứa trẻ nào tự tìm tới hộp bút màu trong giờ chơi tự do. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được chia làm ba nhóm. Nhóm thứ nhất được hứa một tấm giấy khen nếu chịu vẽ. Nhóm thứ hai vẽ xong mới bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Hai tuần sau, hộp bút màu quay lại lớp học. Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: đừng kể xong rồi đi giảng bài. tìm cho ra chỗ khó chịu thật sự nằm ở đâu.)",
								"s": "ins"
							}
						]
					}
				]
			},
			{
				"r": "r02",
				"n": 2,
				"date": "2026-08-16T19:49:52+07:00",
				"words": 349,
				"note": "tìm ra rồi: khác nhau chỉ là một câu nói. cái gây hại là lời hứa, không phải phần thưởng.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "editing"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "notes"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem đứa trẻ nào tự tìm tới hộp bút màu trong giờ chơi tự do. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được chia làm ba nhóm. Nhóm thứ nhất được hứa một tấm giấy khen nếu chịu vẽ. Nhóm thứ hai vẽ xong mới bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Hai tuần sau, hộp bút màu quay lại lớp học. Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": "",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: chỗ này cần một cái tên. hiện tượng này chắc chắn có tên rồi.)",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: đừng kể xong rồi đi giảng bài. tìm cho ra chỗ khó chịu thật sự nằm ở đâu.)",
								"s": "del"
							}
						]
					}
				]
			},
			{
				"r": "r03",
				"n": 3,
				"date": "2026-08-16T19:50:26+07:00",
				"words": 536,
				"note": "có tên rồi: biện minh quá mức. thêm được câu về phản hồi — sợ người đọc tưởng mình bảo đừng khen ai bao giờ.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "editing"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, và hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, và cách xếp loại đó ở lại sau khi phần thưởng đã biến mất.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn. Biện minh quá mức. Không phải thiếu lý do, mà thừa lý do. Có thêm một lý do bên ngoài đủ tốt, thì lý do bên trong thành ra không cần thiết nữa, và cái không cần thiết thì mờ dần.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi phản hồi đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, và thông tin không thay chỗ của lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: chỗ này cần một cái tên. hiện tượng này chắc chắn có tên rồi.)",
								"s": "del"
							}
						]
					}
				]
			},
			{
				"r": "r04",
				"n": 4,
				"date": "2026-08-16T19:51:11+07:00",
				"words": 667,
				"note": "quay câu cuối về phía người đọc. còn mục V — chưa biết nói gì mà không thành lời khuyên.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "settled"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "editing"
					},
					{
						"label": "V. Vậy thì làm gì với chuyện này",
						"state": "notes",
						"notes": [
							"Nếu phần thưởng hỏng việc, chẳng lẽ không bao giờ được thưởng ai? Mình không tin thế, nhưng chưa nói được cho gọn.",
							"Người lớn tự hứa với chính mình thì có tính là hợp đồng không? Thí nghiệm không trả lời chỗ này.",
							"Cẩn thận: mục này rất dễ trượt thành một bài self-help. Nếu không viết được mà không lên giọng khuyên bảo thì bỏ hẳn."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, và hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó."
							},
							{
								"t": " Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, và cách xếp loại đó ở lại sau khi phần thưởng đã biến mất."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn. Biện minh quá mức. Không phải thiếu lý do, mà thừa lý do. Có thêm một lý do bên ngoài đủ tốt, thì lý do bên trong thành ra không cần thiết nữa, và cái không cần thiết thì mờ dần."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi phản hồi đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, và thông tin không thay chỗ của lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn mình muốn. Không ai bắt chúng vẽ, không ai phạt chúng, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, và chúng đi qua.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bây giờ thử nhớ lại lần gần nhất bạn nói với chính mình rằng viết xong cái này thì sẽ có người đọc, chạy đủ tháng này thì sẽ đạt mục tiêu. Câu đó được nói ra trước hay sau khi bạn bắt đầu.",
								"s": "ins"
							}
						]
					}
				]
			},
			{
				"r": "r05",
				"n": 5,
				"date": "2026-08-17T08:02:35+07:00",
				"words": 802,
				"note": "quay câu cuối về phía người đọc. còn mục V — chưa biết nói gì mà không thành lời khuyên.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "settled"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "editing"
					},
					{
						"label": "V. Vậy thì làm gì với chuyện này",
						"state": "notes",
						"notes": [
							"Nếu phần thưởng hỏng việc, chẳng lẽ không bao giờ được thưởng ai? Mình không tin thế, nhưng chưa nói được cho gọn.",
							"Người lớn tự hứa với chính mình thì có tính là hợp đồng không? Thí nghiệm không trả lời chỗ này.",
							"Cẩn thận: mục này rất dễ trượt thành một bài self-help. Nếu không viết được mà không lên giọng khuyên bảo thì bỏ hẳn."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một "
							},
							{
								"t": "chiều",
								"s": "del"
							},
							{
								"t": "chiều,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "và",
								"s": "del"
							},
							{
								"t": "ngầm",
								"s": "ins"
							},
							{
								"t": " đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa "
							},
							{
								"t": "một,",
								"s": "del"
							},
							{
								"t": "một",
								"s": "ins"
							},
							{
								"t": " và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi "
							},
							{
								"t": "rằng ",
								"s": "ins"
							},
							{
								"t": "có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba "
							},
							{
								"t": "vẽ,",
								"s": "del"
							},
							{
								"t": "chỉ",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "vẽ ",
								"s": "ins"
							},
							{
								"t": "và không "
							},
							{
								"t": "có",
								"s": "del"
							},
							{
								"t": "nhận",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "được ",
								"s": "ins"
							},
							{
								"t": "gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, "
							},
							{
								"t": "và",
								"s": "del"
							},
							{
								"t": "tiếp",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "đếm",
								"s": "del"
							},
							{
								"t": "tục",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "tiếp.",
								"s": "del"
							},
							{
								"t": "đếm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được "
							},
							{
								"t": "hứa sẽ được ",
								"s": "ins"
							},
							{
								"t": "thưởng gì. Những bức "
							},
							{
								"t": "tranh ",
								"s": "ins"
							},
							{
								"t": "chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao "
							},
							{
								"t": "cả.",
								"s": "del"
							},
							{
								"t": "cả,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Vẫn",
								"s": "del"
							},
							{
								"t": "chúng",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "vẫn ",
								"s": "ins"
							},
							{
								"t": "vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Cái khó chịu nằm ở chỗ nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen. Thứ duy nhất khác nhau là một lời hứa trước khi chúng chúng cầm bút vẽ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này có nghĩa là cái gây hại không phải phần thưởng. Mà là lời hứa về phần thưởng đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó. Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời."
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "cách xếp loại đó ở lại sau khi phần thưởng đã biến mất."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn "
							},
							{
								"t": "nhẫn.",
								"s": "del"
							},
							{
								"t": "nhẫn,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Biện",
								"s": "del"
							},
							{
								"t": "biện",
								"s": "ins"
							},
							{
								"t": " minh quá "
							},
							{
								"t": "mức.",
								"s": "del"
							},
							{
								"t": "mức",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Không",
								"s": "del"
							},
							{
								"t": "(overjustification),",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "không ",
								"s": "ins"
							},
							{
								"t": "phải thiếu lý do, mà "
							},
							{
								"t": "do có ",
								"s": "ins"
							},
							{
								"t": "thừa lý do. "
							},
							{
								"t": "Có",
								"s": "del"
							},
							{
								"t": "_Có",
								"s": "ins"
							},
							{
								"t": " thêm một lý do bên ngoài đủ "
							},
							{
								"t": "tốt,",
								"s": "del"
							},
							{
								"t": "tốt",
								"s": "ins"
							},
							{
								"t": " thì lý do bên trong thành ra không cần thiết "
							},
							{
								"t": "nữa,",
								"s": "del"
							},
							{
								"t": "nữa_",
								"s": "ins"
							},
							{
								"t": " và cái không cần thiết thì "
							},
							{
								"t": "sẽ lu ",
								"s": "ins"
							},
							{
								"t": "mờ dần."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi "
							},
							{
								"t": "vòng ",
								"s": "ins"
							},
							{
								"t": "phản hồi "
							},
							{
								"t": "đến từ bên ngoài ",
								"s": "ins"
							},
							{
								"t": "đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "thông tin không thay chỗ "
							},
							{
								"t": "của",
								"s": "del"
							},
							{
								"t": "cho",
								"s": "ins"
							},
							{
								"t": " lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn. Vốn ban đầu chúng thích vẽ và vẽ cũng chỉ vì thích, rồi khi vào thí nghiệm, không ai bắt chúng vẽ, không ai phạt, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, chúng ít vẽ dần đi. Điều này cũng khá giống chúng ta, ban đầu vốn thích làm cái gì đó bởi vì lý do tự thân bên trong chúng hoặc bên trong chúng ta, nhưng rồi có những lý do khác bên ngoài xuất hiện, rồi thay thế vị trí đó, cụ thể với mình là **code**, từ đầu mình thích code vì chính nó, vì sự tò mò cá nhân, vì cảm giác tự tạo ra cái gì đó của riêng mình. Nhưng rồi vào môi trường chuyên nghiệp, với KPI, đo lường, performance, khen thưởng,...vv, mình ít thích code dần. Có lẽ có một \"lời hứa\" nào đó đã thế chỗ cho lý do nội tại bên trong mình.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bạn hãy thử nhớ lại lần gần nhất bạn làm một việc gì đó chỉ vì chính nó hoặc chính bản thân bạn, có thể là đọc sách, học đàn, học vẽ, học võ, học bơi, leo núi,...vv.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn mình muốn. Không ai bắt chúng vẽ, không ai phạt chúng, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, và chúng đi qua.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bây giờ thử nhớ lại lần gần nhất bạn nói với chính mình rằng viết xong cái này thì sẽ có người đọc, chạy đủ tháng này thì sẽ đạt mục tiêu. Câu đó được nói ra trước hay sau khi bạn bắt đầu.",
								"s": "del"
							}
						]
					}
				]
			},
			{
				"r": "r06",
				"n": 6,
				"date": "2026-08-17T08:05:43+07:00",
				"words": 802,
				"note": "quay câu cuối về phía người đọc. còn mục V — chưa biết nói gì mà không thành lời khuyên.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "editing"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "editing"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "editing"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "editing"
					},
					{
						"label": "V. Vậy thì làm gì với chuyện này",
						"state": "notes",
						"notes": [
							"Nếu phần thưởng hỏng việc, chẳng lẽ không bao giờ được thưởng ai? Mình không tin thế, nhưng chưa nói được cho gọn.",
							"Người lớn tự hứa với chính mình thì có tính là hợp đồng không? Thí nghiệm không trả lời chỗ này.",
							"Cẩn thận: mục này rất dễ trượt thành một bài self-help. Nếu không viết được mà không lên giọng khuyên bảo thì bỏ hẳn."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều, ngầm đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi rằng có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba chỉ vẽ và không nhận được gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, tiếp tục đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được hứa sẽ được thưởng gì. Những bức tranh chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả, chúng vẫn vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Cái khó chịu nằm ở chỗ nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen. Thứ duy nhất khác nhau là một lời hứa trước khi chúng chúng cầm bút vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này có nghĩa là cái gây hại không phải phần thưởng. Mà là lời hứa về phần thưởng đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó. Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời."
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, cách xếp loại đó ở lại sau khi phần thưởng đã biến mất."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn, biện minh quá mức (overjustification), không phải thiếu lý do, mà do có thừa lý do. _Có thêm một lý do bên ngoài đủ tốt thì lý do bên trong thành ra không cần thiết nữa_ và cái không cần thiết thì sẽ lu mờ dần."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi vòng phản hồi đến từ bên ngoài đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, thông tin không thay chỗ cho lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn. Vốn ban đầu chúng thích vẽ và vẽ cũng chỉ vì thích, rồi khi vào thí nghiệm, không ai bắt chúng vẽ, không ai phạt, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, chúng ít vẽ dần đi. Điều này cũng khá giống chúng ta, ban đầu vốn thích làm cái gì đó bởi vì lý do tự thân bên trong chúng hoặc bên trong chúng ta, nhưng rồi có những lý do khác bên ngoài xuất hiện, rồi thay thế vị trí đó, cụ thể với mình là **code**, từ đầu mình thích code vì chính nó, vì sự tò mò cá nhân, vì cảm giác tự tạo ra cái gì đó của riêng mình. Nhưng rồi vào môi trường chuyên nghiệp, với KPI, đo lường, performance, khen thưởng,...vv, mình ít thích code dần. Có lẽ có một \"lời hứa\" nào đó đã thế chỗ cho lý do nội tại bên trong mình."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bạn hãy thử nhớ lại lần gần nhất bạn làm một việc gì đó chỉ vì chính nó hoặc chính bản thân bạn, có thể là đọc sách, học đàn, học vẽ, học võ, học bơi, leo núi,...vv."
							}
						]
					}
				]
			},
			{
				"r": "r11",
				"n": 11,
				"date": "2026-08-19T21:53:06+07:00",
				"words": 700,
				"note": "Chưa chốt bản final.",
				"sections": [
					{
						"label": "I. Niềm vui thuần túy",
						"state": "editing"
					},
					{
						"label": "II. Biện minh quá mức",
						"state": "editing"
					},
					{
						"label": "III. Vậy phải làm sao?",
						"state": "editing"
					},
					{
						"label": "IV. Notes",
						"state": "notes",
						"notes": [
							"Còn bỏ ngõ, làm sao để thoát khỏi sự vô vị này.",
							"À, người lớn có overjustification không? Thí nghiệm không trả lời chỗ này."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Hôm nay mình có vài suy nghĩ vu vơ: \"Tại sao code lại không còn vui như trước nữa?\". Cái niềm vui mà mình gọi là _niềm vui thuần túy_.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Niềm vui thuần túy là niềm vui đến từ chính bản thân việc đó. Giống như những ngày đầu mình code, mình làm nó vì vui, vì tò mò, vì cái cảm giác tạo ra cái gì đó của riêng mình từ hư không. Niềm vui này không chỉ đi kèm với sự thành công hay dễ dàng, nó đi kèm cả những khi khó khăn. Như lúc bắt đầu code, mình đâu có kiến thức gì bài bản đâu, chỉ là vài kiến thức góp nhặt từ các khóa học ngắn, rồi thuật toán, công nghệ, bug, có thể nói là vô cùng khó khăn, nhưng mình vẫn vui, rất vui vào lúc đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình cảm thấy rằng, từ từ mình đang mất đi những niềm vui thuần túy như vậy. Bây giờ làm việc gì cũng cần có thước đo, so sánh, chỉ báo bên ngoài để làm lý do cho nó, làm phải năng suất, phải nhanh, phải tốt. Quay về chuyên môn của mình, code, mình đã vào môi trường chuyên nghiệp của ngành phần mềm này đã hơn bảy năm, tình hình là, code với mình bớt vui dần. Code giờ có KPI, đo story point (một vấn đề vận hành mà mình sẽ nói trong bài khác), performance review, khen thưởng, có cấp bậc, ...vv. Bản thân việc code không khác đi, nhưng có lẽ mình đã lấy lý do nào đó bên ngoài để thay thế cho lý do bên trong nên từ từ cả sự \"thuần túy\" và \"niềm vui\" đều nhạt đi.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Trong lúc mình tìm hiểu rõ về hiện tượng này thì phát hiện ra đây không phải là cái gì đó mới, người ta đã có nghiên cứu về nó cách đây rất lâu và nó cũng có một cái tên \"Biện minh quá mức (Overjustification)\".",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Vào năm 1973, tại một trường mầm non ở Stanford, người ta đã tiến hành một thí nghiệm với các trẻ em thích vẽ, để xem biểu hiện của sự thích vẽ có bị thay đổi với các điều kiện bên ngoài hay không. Các bé từ 40-64 tháng tuổi được chia thành ba nhóm, nhóm 1, được đề nghị là sau khi các bẽ vẽ xong sẽ được nhận một tờ giấy khen (phần thưởng), nhóm 2, được đề nghị là sau khi các bé vẽ xong sẽ có thể nhận được giấy khen hoặc không, nhóm 3, không được đề nghị gì cả.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều, ngầm đếm.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một và chia làm ba nhóm.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi rằng có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba chỉ vẽ và không nhận được gì cả.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, tiếp tục đếm.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được hứa sẽ được thưởng gì. Những bức tranh chúng vẽ cũng bị chấm là kém hơn trước.",
								"s": "del"
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, "
							},
							{
								"t": "M.",
								"s": "del"
							},
							{
								"t": "Mark",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "R.,",
								"s": "del"
							},
							{
								"t": "R.;",
								"s": "ins"
							},
							{
								"t": " Greene, "
							},
							{
								"t": "D., &",
								"s": "del"
							},
							{
								"t": "David;",
								"s": "ins"
							},
							{
								"t": " Nisbett, "
							},
							{
								"t": "R.",
								"s": "del"
							},
							{
								"t": "Richard",
								"s": "ins"
							},
							{
								"t": " E. "
							},
							{
								"t": "(1973). _Undermining",
								"s": "del"
							},
							{
								"t": "Undermining",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "children's",
								"s": "del"
							},
							{
								"t": "children’s",
								"s": "ins"
							},
							{
								"t": " intrinsic interest with extrinsic reward: A test of the "
							},
							{
								"t": "\"overjustification\"",
								"s": "del"
							},
							{
								"t": "“overjustification”",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "hypothesis_.",
								"s": "del"
							},
							{
								"t": "hypothesis.",
								"s": "ins"
							},
							{
								"t": " Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Sau hai tuần quan sát, kết quả là nhóm 1 ít vẽ lại hơn hẵn so với ban đầu, và chất lượng bức tranh có vẽ thấp hơn, nhóm 2, 3 giữ nguyên số lượng. Điều đáng chú ý là nhóm 1, 2 đều sẽ có giấy khen, nên thứ tạo ra khác biệt này không phải là phần thưởng mà là lời lứa về phần thưởng đó. Lý do bên ngoài là \"giấy khen\" đã được các bé thay cho lý do bên trong lúc đầu.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Có lẽ mình cũng là một đứa trẻ ở nhóm 1, chỉ khác số tháng tuổi và \"lời hứa\" mình đã nhận vào bên trong.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhưng, vậy thì rồi sao? Nếu cứ để như vậy thì cuộc sống này cuối cùng cũng chỉ còn là những thứ nhàm chán vô vị sao?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Well, thú thật mình cũng đang đi tìm câu trả lời làm sao để thoát ra khỏi cái này. Có lẽ là một lý do nội tại siêu mạnh để không bị thay thế, cũng có thể chỉ đơn giản là mặc kệ lời hứa được offer. Nhưng vẫn chưa có kết luận cụ thể theo trải nghiệm bản thân, xin phép bỏ ngõ nó ở đây.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả, chúng vẫn vẽ như cũ.",
								"s": "del"
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": "",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Cái khó chịu nằm ở chỗ nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen. Thứ duy nhất khác nhau là một lời hứa trước khi chúng chúng cầm bút vẽ.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này có nghĩa là cái gây hại không phải phần thưởng. Mà là lời hứa về phần thưởng đó.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó. Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời.",
								"s": "del"
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, cách xếp loại đó ở lại sau khi phần thưởng đã biến mất.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn, biện minh quá mức (overjustification), không phải thiếu lý do, mà do có thừa lý do. _Có thêm một lý do bên ngoài đủ tốt thì lý do bên trong thành ra không cần thiết nữa_ và cái không cần thiết thì sẽ lu mờ dần.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi vòng phản hồi đến từ bên ngoài đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, thông tin không thay chỗ cho lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn. Vốn ban đầu chúng thích vẽ và vẽ cũng chỉ vì thích, rồi khi vào thí nghiệm, không ai bắt chúng vẽ, không ai phạt, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, chúng ít vẽ dần đi. Điều này cũng khá giống chúng ta, ban đầu vốn thích làm cái gì đó bởi vì lý do tự thân bên trong chúng hoặc bên trong chúng ta, nhưng rồi có những lý do khác bên ngoài xuất hiện, rồi thay thế vị trí đó, cụ thể với mình là **code**, từ đầu mình thích code vì chính nó, vì sự tò mò cá nhân, vì cảm giác tự tạo ra cái gì đó của riêng mình. Nhưng rồi vào môi trường chuyên nghiệp, với KPI, đo lường, performance, khen thưởng,...vv, mình ít thích code dần. Có lẽ có một \"lời hứa\" nào đó đã thế chỗ cho lý do nội tại bên trong mình.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Well, vậy phải làm sao với chuyện này? Nếu cứ để như vậy, chẳng phải mọi thứ rồi sẽ dần mất vui và nhàm chán sao?",
								"s": "del"
							}
						]
					}
				]
			}
		]
	},
	"004-AI-empowerment-counting-by-SP-en": {
		"edits": 1,
		"startedAt": "2026-08-19",
		"promise": "no promises",
		"current": "r01",
		"revisions": [
			{
				"r": "r01",
				"n": 1,
				"date": "2026-08-20T22:30:20+07:00",
				"words": 2191,
				"note": "English edition of the Vietnamese piece; section IV and the conclusion are freshly translated",
				"sections": [
					{
						"label": "I. Velocity and the basic arithmetic",
						"state": "editing"
					},
					{
						"label": "II. Comparing two series",
						"state": "editing"
					},
					{
						"label": "III. How big does a difference have to be?",
						"state": "editing"
					},
					{
						"label": "IV. So how long does it take?",
						"state": "editing"
					},
					{
						"label": "V. Conclusion",
						"state": "editing"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "One of the companies I worked at leaned on AI heavily across the whole Software Development Life Cycle (SDLC). Using that much AI is a form of investment, so the CEO asked for productivity to improve by 10% every quarter — and productivity, on the R&D (Research and Development) side, was measured in story points (SP). Whether the story point is the right way to measure productivity is a different argument and this piece will not have it; assume it is. The question here is narrower: is \"10% growth every quarter\" something you can actually establish?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "## Velocity and the basic arithmetic",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "In software the word \"productivity\" usually turns into the word \"velocity\", and velocity is measured as the number of SP finished in one sprint. Productivity over a quarter, then, is many sprints — which means it is not a single number at all. It is a series.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Here is Q1, as logged:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "``` 38   45   31   42   36   48 ```",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "What can we pull out of that?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The mean is $\\mu_1=40$, and yet not one sprint was 40. The gap between the best sprint and the worst is $48-31=17$ SP, and nothing on the outside changed across those twelve weeks: same people, same codebase, same way of working.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "So the first thing to accept is that **velocity swings even when nothing is happening**. Not big changes — small ones. Somebody was off sick. A story turned out easier than it looked, or harder.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "That swing has a size, and the sample standard deviation is how you get at it: $$\\sigma_1 = \\sqrt{\\frac{1}{N-1} \\sum_{i=1}^{N}(x_i - \\mu_1)^2}$$ With $N=6$ and the series above, $\\sigma_1=6.23$, and the sample variance is $s_1^2=38.8$. A lot of numbers, I know. The short version: **with nothing whatsoever going on, a sprint can land 6.23 points off the mean.**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "One more number falls out of the same data, the coefficient of variation $c$: $$c_1=\\frac{\\sigma_1}{\\mu_1}=\\frac{6.23}{40}=0.156$$ which says that **this team's ordinary swing is about 15.6% of its own average**. As teams go, that is a steady one.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "## Comparing two series",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The question at the end is not any of the numbers above — trust me, they matter — it is a comparison between two series.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Q2 comes in, and the log now reads:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "``` Q1: 38  45  31  42  36  48   →  avg: 40.0 Q2: 41  49  36  47  40  51   →  avg: 44.0 ```",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Q2's average is 4 points above Q1's. Exactly 10%. Time to celebrate?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Celebrate first, sure. But then: **if nothing at all had acted on this team, AI included, could a 4-point gap have shown up anyway?**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The usual way to compare two series is to compare their means, which is what we just did — and a mean carries an error of its own, the standard error of the mean: $$SE_1=\\frac{\\sigma_1}{\\sqrt{N}}=\\frac{6.23}{\\sqrt{6}}=2.54$$ What that number says is this: if you had the power to re-run Q1 in some other timeline, same team, same conditions, the mean $\\mu_1$ (40) coming out 2.54 points different would be an ordinary Tuesday.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "So if we could re-run *both* quarters in another timeline, how far apart could the two means land?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "<ReRun mu={40} sd={[6.23, 5.87]} n={6} at={4} atLabel=\"+4 — what we actually observed\" axisLabel=\"difference between the two quarterly means (points)\" readout={\"You have re-run it {runs} times, in a world where nothing changed at all — no AI, no improvement, nothing. {hits} of those came out {at} points or more.\"} label=\"Figure 2\" hint=\"re-run the quarter\" caption=\"Each dot is a quarter lived again: two runs of six sprints drawn from the same team, the same spread, with no improvement anywhere in it. The orange dots are the times noise alone built 'evidence' as large as the evidence we actually have.\" alt=\"Dots fall around zero in a bell shape; those at +4 and beyond are inked in a second colour.\" />",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "With $SE_2=\\frac{\\sigma_2}{\\sqrt{N}}=\\frac{5.87}{\\sqrt{6}}=2.39$,",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$SE=\\sqrt{SE_1^2+SE_2^2}=\\sqrt{2.54^2+2.39^2}=3.49$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Which gives us something to say: **with nothing changed at all, two quarterly means drifting 3.49 points apart is normal.** The gap we observed is 4 points, and noise alone reaches 3.5. The quick conclusion is the honest one — there is not enough here to say whether AI helped, because what we are holding is barely distinguishable from noise.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "## How big does a difference have to be?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Before the arithmetic, one more thing about that $SE$: it is also the width of the bell the noise is spread along. Go back to re-running both quarters in another timeline — do that endlessly and about 70% of the time the difference lands between -3.49 and 3.49 points.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "<NormalCurve sd={3.49} bandLabel=\"about 70% of runs land in here\" bandTick=\"±SE = 3.49\" axisLabel=\"difference between the two quarterly means (points)\" marks={[{ at: 4, label: 'observed difference: +4' }]} label=\"Figure 1\" hint=\"the noise distribution\" caption=\"With nothing changed, the gap between two quarters still wanders around zero with a width of SE = 3.49. The +4 we observed sits well inside that cloud.\" alt=\"A normal curve centred on zero, shaded from -3.49 to 3.49 points, with a mark at +4 just past the edge of the shading.\" />",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "To detect anything and mean it, there are two ways to be wrong, and both have to be guarded against.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "### Type I error",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "A type I error is a false alarm: nothing changed, but noise happened to throw up a gap wider than the ordinary one we just measured (3.49). To guard against it, we allow only a 5% chance of noise clearing the bar — and on a normal curve that point sits 1.96 widths out from the centre. So the bar is $1.96\\times3.49=6.84\\approx7$, which means: **under 7 points, say nothing.**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "<Sidenote>",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The 1.96 belongs to the normal distribution and holds when the sample is large. Here each quarter is six sprints, and $\\sigma$ is itself estimated from those same six numbers, so strictly this calls for the _t_ distribution with Welch's degrees of freedom — 10 here — and a factor of 2.23 rather than 1.96. The bar moves from 7 to 8, and $\\Delta_{min}$ below from 10 to 11. This piece keeps 1.96 to keep the thread clean, because the conclusion does not move: the 10% being asked for (4 points) sits under both bars.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "</Sidenote>",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "### Type II error",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "A type II error is a miss: the improvement was real, but noise dragged the number below the bar and it got read as \"nothing happened\". Concretely — if the real improvement is exactly the 7 points we just computed, then across endless re-runs you catch it half the time and lose it the other half. To push the catch rate to 80%, the real improvement has to clear 7 by a margin: on a bell, shifting the centre 0.84 widths further puts 80% of the distribution to the right of the bar.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "So what is needed is $$\\Delta_{min}=(1.96+0.84)\\times SE=2.8\\times 3.49=9.77\\approx 10$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Which is to say, **a gap of at least 10 points before it counts as improvement.**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "<DetectionPower se={3.49} presets={[ { label: 'the bar', at: 6.84 }, { label: '80%', at: 9.77 } ]} thresholdLabel=\"the bar: 6.84\" axisLabel=\"difference between the two quarterly means (points)\" readout={\"If the real improvement is exactly {delta} points, then across endless re-runs you would call it an improvement about {power} of the time. The shaded tail is that share.\"} label=\"Figure 3\" hint=\"drag it\" caption=\"The grey bell standing still is noise. The blue one is a world where the improvement is real — drag it wherever you like. Park it on the bar and the shaded part is exactly half: that is where the 50% goes missing.\" alt=\"Two normal curves of equal width, one centred on zero and one moved by a slider, with a threshold rule and a shaded tail.\" />",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "## So how long does it take?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Let me restate the question. We know a gap has to reach at least 10 points before it counts, and we collected $N=6$ per quarter. The new question is **\"how many sprints (N) does it take to establish that the team improved by 10%?\"**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "### Generalising SE",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The $SE=3.49$ from earlier is one specific number for $n=6$, not a formula. Assuming the two series are always the same length, it can be written out:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$SE=\\sqrt{SE_1^2 + SE_2^2} = \\sqrt{\\frac{\\sigma_1^2}{n} + \\frac{\\sigma_2^2}{n}} = \\sqrt{\\frac{\\sigma_1^2 + \\sigma_2^2}{n}} = \\sqrt{\\frac{2}{n} \\times \\frac{\\sigma_1^2 + \\sigma_2^2}{2}} = \\sigma_{pooled} \\times \\sqrt{\\frac{2}{n}}$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "where",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$\\sigma_{pooled}=\\sqrt{\\frac{\\sigma_1^2 + \\sigma_2^2}{2}} = \\sqrt{\\frac{38.8 + 34.4}{2}} = \\sqrt{36.6} = 6.05$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "### Working the threshold backwards",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "We also have $\\Delta_{min}=2.8 \\times SE \\approx 10$ as the point where a gap counts. Substituting the formula for $SE$ gives an inequality:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$\\Delta \\geq 2.8 \\times SE = 2.8 \\times \\sigma\\sqrt{\\frac{2}{n}}$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "In words: **a real improvement has to be at least 2.8 times the noise of the comparison.**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Now rearrange it for $n$.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$\\Delta\\geq2.8\\times\\sigma\\times\\sqrt{\\frac{2}{n}} \\Leftrightarrow \\Delta^2\\geq2.8^2\\times\\sigma^2\\times\\frac{2}{n} \\Leftrightarrow \\Delta^2\\geq\\frac{15.7\\times\\sigma^2}{n} \\Leftrightarrow n \\geq \\frac{15.7\\times\\sigma^2}{\\Delta^2}$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "That is a formula for $n$, but not yet one in percentages. To get there, divide top and bottom by $\\mu^2$ — the square of the series' mean.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "n \\geq \\frac{15.7\\times\\left(\\frac{\\sigma^2}{\\mu^2}\\right)}{\\left(\\frac{\\Delta^2}{\\mu^2}\\right)}",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "\\Leftrightarrow n \\geq \\frac{15.7\\times(\\sigma/\\mu)^2}{\\Delta^2/\\mu^2}",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "\\Leftrightarrow n \\geq \\frac{15.7\\times c^2}{(\\Delta/\\mu)^2}",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "And $\\sigma/\\mu=c$ is the team's coefficient of variation. So what does the formula say?",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "The numerator says _how much noise, in percent, this team brings_. The denominator says _how much improvement, in percent, you want to catch_.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "With the pooled $c$ across both quarters, $c=\\frac{\\sigma_{pooled}}{\\mu_{pooled}}=\\frac{6.05}{42}=0.144$, and a 10% improvement to catch, so $\\Delta/\\mu=0.1$, $n$ has to be",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "$$ n \\geq \\frac{15.7 \\times 0.144^2}{0.1^2} \\approx 32.5 $$",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "#### A quick check",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Put $n=33$ back into the formula for SE: $SE=\\sigma\\times\\sqrt{\\frac{2}{n}}=6.05\\times\\sqrt{\\frac{2}{33}}\\approx1.49$. That gives $\\Delta_{min}=2.8 \\times SE=2.8\\times1.49=4.17$, and $4.17/\\mu_{pooled}=4.17/42=0.099=9.9\\%$. Good — the arithmetic holds.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "So it takes at least **33 sprints per arm**, meaning **66 sprints**, before you can catch whether something has lifted productivity by 10%.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "## Conclusion",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Back to the CEO's question: \"productivity has to improve 10% every quarter\". The answer is not \"yes\" or \"no\". It is something more uncomfortable: **with one quarter of data, that question has no answer at all.**",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Three numbers from this piece, side by side, say the whole thing:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "- The team already swings **15%** around its own average when nothing is happening. - The gap to reach is **4 points**; the noise of the comparison is **3.49 points**. What we need to measure is barely distinguishable from pure noise. - To tell those two apart takes **33 sprints per arm** — with two-week sprints, two and a half years of data for **one** conclusion.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Here is the paradox. The review cycle is a quarter, six sprints, while the measure being used to do the reviewing needs ten times that before it can conclude anything. Asking for \"10% a quarter\" is not wrong as an expectation. It is just **not verifiable in story points** — and an unverifiable demand gets answered each quarter by instinct, by a number that happened to look good, or by whoever was loudest in the meeting.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "If you still want to measure it, the formula $n \\geq \\frac{15.7 \\times c^2}{(\\Delta/\\mu)^2}$ leaves exactly three knobs:",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "1. **Cut $c$ — make the team less noisy.** $n$ scales with $c^2$, so the steadier the team the less time it takes: pull the swing from 15% down to 7.5% and the wait drops to **a quarter** of what it was. Stories split small and evenly, estimates kept consistent, no changing the scale halfway through. This turns out to be the most valuable work on the list, and it has almost nothing to do with AI. 2. **Accept a bigger target.** $n$ scales inversely with $(\\Delta/\\mu)^2$, so hunting a 20% improvement costs a quarter of what hunting 10% costs. A genuinely large effect is easier to prove than a small one is to evidence. 3. **Widen the observation window.** Stop asking \"did we grow 10% this quarter\"; ask \"after a year and a half, has the trend actually turned\".",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "And the last one, which matters most: none of the numbers above **conclude anything about whether AI is useful**. They say story points are not sensitive enough to serve as evidence for the question being asked. Those are two entirely different statements — and in an end-of-quarter review they get treated as one.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "<SampleSizeGrid first=\"38 45 31 42 36 48\" second=\"41 49 36 47 40 51\" unitLabel=\"sprints to observe, per arm\" readoutEnough={\"Your team swings {c} around its mean. The observed difference is {diff} points against a bar of {thr} points — enough to call it an improvement. To catch the level you picked, you need {n} sprints per arm, about {months} months.\"} readoutShort={\"Your team swings {c} around its mean. The observed difference is {diff} points against a bar of {thr} points — not enough to say anything yet. To catch the level you picked, you need {n} sprints per arm, about {months} months.\"} label=\"Figure 4\" hint=\"your team's numbers\" caption=\"Two levers, both squared: halve the team's swing, or double the improvement you need to catch, and either one cuts the wait to a quarter. The filled cell is where the team in this piece stands.\" alt=\"A table of sprints to observe: rows are the improvement you want to catch, columns are how much the team varies.\" />",
								"s": "ins"
							}
						]
					}
				]
			}
		]
	}
};
