/**
 * The open drafts, as git remembers them.
 *
 * GENERATED by `node scripts/drafts.mjs` — do not edit. The author's words in
 * here (a revision's note, its section states) come from the frontmatter of the
 * commit that saved it; everything else is computed.
 *
 * Plain `.js` for the same reason as `glossary.data.js`: the types live next
 * door in `drafts.ts`, which re-exports this, and JSDoc keeps checking.
 *
 * @type {import('./drafts').Drafts}
 */
export const DRAFTS = {
	"003-pure-joy-vi": {
		"edits": 5,
		"startedAt": "2026-08-16",
		"promise": "chưa hứa",
		"current": "r05",
		"revisions": [
			{
				"r": "r01",
				"n": 1,
				"sha": "6fa7e4cd7",
				"date": "2026-08-16T19:49:27+07:00",
				"words": 139,
				"note": "mới chỉ có cái thí nghiệm. chưa biết mình muốn nói gì về nó.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "editing"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "notes"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "notes"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem đứa trẻ nào tự tìm tới hộp bút màu trong giờ chơi tự do. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được chia làm ba nhóm. Nhóm thứ nhất được hứa một tấm giấy khen nếu chịu vẽ. Nhóm thứ hai vẽ xong mới bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Hai tuần sau, hộp bút màu quay lại lớp học. Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: đừng kể xong rồi đi giảng bài. tìm cho ra chỗ khó chịu thật sự nằm ở đâu.)",
								"s": "ins"
							}
						]
					}
				]
			},
			{
				"r": "r02",
				"n": 2,
				"sha": "b558d57c2",
				"date": "2026-08-16T19:49:52+07:00",
				"words": 349,
				"note": "tìm ra rồi: khác nhau chỉ là một câu nói. cái gây hại là lời hứa, không phải phần thưởng.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "editing"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "notes"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem đứa trẻ nào tự tìm tới hộp bút màu trong giờ chơi tự do. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được chia làm ba nhóm. Nhóm thứ nhất được hứa một tấm giấy khen nếu chịu vẽ. Nhóm thứ hai vẽ xong mới bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Hai tuần sau, hộp bút màu quay lại lớp học. Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": "",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: chỗ này cần một cái tên. hiện tượng này chắc chắn có tên rồi.)",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: đừng kể xong rồi đi giảng bài. tìm cho ra chỗ khó chịu thật sự nằm ở đâu.)",
								"s": "del"
							}
						]
					}
				]
			},
			{
				"r": "r03",
				"n": 3,
				"sha": "9c564c389",
				"date": "2026-08-16T19:50:26+07:00",
				"words": 536,
				"note": "có tên rồi: biện minh quá mức. thêm được câu về phản hồi — sợ người đọc tưởng mình bảo đừng khen ai bao giờ.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "editing"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "notes"
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, và hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, và cách xếp loại đó ở lại sau khi phần thưởng đã biến mất.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn. Biện minh quá mức. Không phải thiếu lý do, mà thừa lý do. Có thêm một lý do bên ngoài đủ tốt, thì lý do bên trong thành ra không cần thiết nữa, và cái không cần thiết thì mờ dần.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi phản hồi đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, và thông tin không thay chỗ của lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "(ghi chú: chỗ này cần một cái tên. hiện tượng này chắc chắn có tên rồi.)",
								"s": "del"
							}
						]
					}
				]
			},
			{
				"r": "r04",
				"n": 4,
				"sha": "888a3335f",
				"date": "2026-08-16T19:51:11+07:00",
				"words": 667,
				"note": "quay câu cuối về phía người đọc. còn mục V — chưa biết nói gì mà không thành lời khuyên.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "settled"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "editing"
					},
					{
						"label": "V. Vậy thì làm gì với chuyện này",
						"state": "notes",
						"notes": [
							"Nếu phần thưởng hỏng việc, chẳng lẽ không bao giờ được thưởng ai? Mình không tin thế, nhưng chưa nói được cho gọn.",
							"Người lớn tự hứa với chính mình thì có tính là hợp đồng không? Thí nghiệm không trả lời chỗ này.",
							"Cẩn thận: mục này rất dễ trượt thành một bài self-help. Nếu không viết được mà không lên giọng khuyên bảo thì bỏ hẳn."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một chiều và đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa một, và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba vẽ, và không có gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, và đếm tiếp."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được thưởng gì. Những bức chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao cả. Vẫn vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, và hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó."
							},
							{
								"t": " Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, và cách xếp loại đó ở lại sau khi phần thưởng đã biến mất."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn nhẫn. Biện minh quá mức. Không phải thiếu lý do, mà thừa lý do. Có thêm một lý do bên ngoài đủ tốt, thì lý do bên trong thành ra không cần thiết nữa, và cái không cần thiết thì mờ dần."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi phản hồi đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, và thông tin không thay chỗ của lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn mình muốn. Không ai bắt chúng vẽ, không ai phạt chúng, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, và chúng đi qua.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bây giờ thử nhớ lại lần gần nhất bạn nói với chính mình rằng viết xong cái này thì sẽ có người đọc, chạy đủ tháng này thì sẽ đạt mục tiêu. Câu đó được nói ra trước hay sau khi bạn bắt đầu.",
								"s": "ins"
							}
						]
					}
				]
			},
			{
				"r": "r05",
				"n": 5,
				"sha": "a452647e9",
				"date": "2026-08-17T08:02:35+07:00",
				"words": 802,
				"note": "quay câu cuối về phía người đọc. còn mục V — chưa biết nói gì mà không thành lời khuyên.",
				"sections": [
					{
						"label": "I. Ba nhóm trẻ và hộp bút màu",
						"state": "settled"
					},
					{
						"label": "II. Thứ khác nhau chỉ là một câu nói",
						"state": "settled"
					},
					{
						"label": "III. Biện minh quá mức",
						"state": "settled"
					},
					{
						"label": "IV. Nhóm thứ nhất, và mình",
						"state": "editing"
					},
					{
						"label": "V. Vậy thì làm gì với chuyện này",
						"state": "notes",
						"notes": [
							"Nếu phần thưởng hỏng việc, chẳng lẽ không bao giờ được thưởng ai? Mình không tin thế, nhưng chưa nói được cho gọn.",
							"Người lớn tự hứa với chính mình thì có tính là hợp đồng không? Thí nghiệm không trả lời chỗ này.",
							"Cẩn thận: mục này rất dễ trượt thành một bài self-help. Nếu không viết được mà không lên giọng khuyên bảo thì bỏ hẳn."
						]
					}
				],
				"body": [
					{
						"kind": "p",
						"segs": [
							{
								"t": "Năm 1973, trong một trường mẫu giáo ở Stanford, ba nhà nghiên cứu ngồi sau tấm kính một "
							},
							{
								"t": "chiều",
								"s": "del"
							},
							{
								"t": "chiều,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "và",
								"s": "del"
							},
							{
								"t": "ngầm",
								"s": "ins"
							},
							{
								"t": " đếm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Họ đếm xem trong giờ chơi tự do, đứa trẻ nào tự tìm tới hộp bút màu. Không ai yêu cầu, không ai chấm điểm, bút màu chỉ nằm đó cùng với đất nặn và mấy thứ khác. Những đứa hay chọn bút màu nhất được đưa vào thí nghiệm, tức là những đứa vốn đã thích vẽ."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Rồi chúng được gọi ra ngoài, từng đứa "
							},
							{
								"t": "một,",
								"s": "del"
							},
							{
								"t": "một",
								"s": "ins"
							},
							{
								"t": " và chia làm ba nhóm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất được cho xem một tấm giấy khen có ngôi sao vàng và dải ruy băng đỏ, được hỏi "
							},
							{
								"t": "rằng ",
								"s": "ins"
							},
							{
								"t": "có muốn vẽ để nhận nó không. Chúng đồng ý, chúng vẽ, chúng nhận giấy khen. Nhóm thứ hai chỉ được mời vẽ, vẽ xong thì bất ngờ được tặng đúng tấm giấy khen đó. Nhóm thứ ba "
							},
							{
								"t": "vẽ,",
								"s": "del"
							},
							{
								"t": "chỉ",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "vẽ ",
								"s": "ins"
							},
							{
								"t": "và không "
							},
							{
								"t": "có",
								"s": "del"
							},
							{
								"t": "nhận",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "được ",
								"s": "ins"
							},
							{
								"t": "gì cả."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Một hai tuần sau, hộp bút màu quay lại lớp học, ba nhà nghiên cứu quay lại sau tấm kính, "
							},
							{
								"t": "và",
								"s": "del"
							},
							{
								"t": "tiếp",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "đếm",
								"s": "del"
							},
							{
								"t": "tục",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "tiếp.",
								"s": "del"
							},
							{
								"t": "đếm.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ nhất vẽ ít hẳn đi. Ít hơn cả nhóm chưa từng được "
							},
							{
								"t": "hứa sẽ được ",
								"s": "ins"
							},
							{
								"t": "thưởng gì. Những bức "
							},
							{
								"t": "tranh ",
								"s": "ins"
							},
							{
								"t": "chúng vẽ cũng bị chấm là kém hơn trước."
							}
						]
					},
					{
						"kind": "aside",
						"segs": [
							{
								"t": "Lepper, M. R., Greene, D., & Nisbett, R. E. (1973). _Undermining children's intrinsic interest with extrinsic reward: A test of the \"overjustification\" hypothesis_. Journal of Personality and Social Psychology, 28(1), 129-137. Trẻ từ 40 đến 64 tháng tuổi, quan sát trong giờ chơi tự do, không có sự hiện diện của người thí nghiệm."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nhóm thứ hai thì không sao "
							},
							{
								"t": "cả.",
								"s": "del"
							},
							{
								"t": "cả,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Vẫn",
								"s": "del"
							},
							{
								"t": "chúng",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "vẫn ",
								"s": "ins"
							},
							{
								"t": "vẽ như cũ."
							}
						]
					},
					{
						"kind": "fleuron",
						"segs": [
							{
								"t": ""
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Chỗ khó chịu nằm ở đây. Nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen, cùng ngôi sao vàng, cùng dải ruy băng. Thứ duy nhất khác nhau là một câu nói, và câu đó được nói ra trước khi đứa trẻ cầm bút.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Cái khó chịu nằm ở chỗ nhóm thứ nhất và nhóm thứ hai nhận cùng một tấm giấy khen. Thứ duy nhất khác nhau là một lời hứa trước khi chúng chúng cầm bút vẽ.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Nghĩa là cái gây hại không phải phần thưởng. Là lời hứa.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này có nghĩa là cái gây hại không phải phần thưởng. Mà là lời hứa về phần thưởng đó.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Khi đứa trẻ đồng ý vẽ để lấy giấy khen, nó vừa ký một hợp đồng nhỏ, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "hợp đồng đó nói rằng vẽ là thứ người ta làm để đổi lấy cái khác. Sau đó nó nhìn lại chính mình đang ngồi vẽ và tự rút ra kết luận về lý do mình ngồi đó. Kết luận ấy không sai theo bất kỳ nghĩa nào. Nó chỉ vừa thay chỗ cho một kết luận khác mà đứa trẻ từng có, thứ mà không ai nói thành lời vì hồi đó chưa cần thành lời."
							}
						]
					},
					{
						"kind": "quote",
						"segs": [
							{
								"t": "Phần thưởng không mua thêm động lực. Nó dạy lại đứa trẻ cách xếp loại việc nó đang làm, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "cách xếp loại đó ở lại sau khi phần thưởng đã biến mất."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Đây là chỗ mà tên gọi của hiện tượng trở nên chính xác một cách hơi tàn "
							},
							{
								"t": "nhẫn.",
								"s": "del"
							},
							{
								"t": "nhẫn,",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Biện",
								"s": "del"
							},
							{
								"t": "biện",
								"s": "ins"
							},
							{
								"t": " minh quá "
							},
							{
								"t": "mức.",
								"s": "del"
							},
							{
								"t": "mức",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "Không",
								"s": "del"
							},
							{
								"t": "(overjustification),",
								"s": "ins"
							},
							{
								"t": " "
							},
							{
								"t": "không ",
								"s": "ins"
							},
							{
								"t": "phải thiếu lý do, mà "
							},
							{
								"t": "do có ",
								"s": "ins"
							},
							{
								"t": "thừa lý do. "
							},
							{
								"t": "Có",
								"s": "del"
							},
							{
								"t": "_Có",
								"s": "ins"
							},
							{
								"t": " thêm một lý do bên ngoài đủ "
							},
							{
								"t": "tốt,",
								"s": "del"
							},
							{
								"t": "tốt",
								"s": "ins"
							},
							{
								"t": " thì lý do bên trong thành ra không cần thiết "
							},
							{
								"t": "nữa,",
								"s": "del"
							},
							{
								"t": "nữa_",
								"s": "ins"
							},
							{
								"t": " và cái không cần thiết thì "
							},
							{
								"t": "sẽ lu ",
								"s": "ins"
							},
							{
								"t": "mờ dần."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Điều này không có nghĩa là mọi "
							},
							{
								"t": "vòng ",
								"s": "ins"
							},
							{
								"t": "phản hồi "
							},
							{
								"t": "đến từ bên ngoài ",
								"s": "ins"
							},
							{
								"t": "đều độc hại. Một lời nói cho biết bạn vừa làm tốt chỗ nào là thông tin, "
							},
							{
								"t": "và ",
								"s": "del"
							},
							{
								"t": "thông tin không thay chỗ "
							},
							{
								"t": "của",
								"s": "del"
							},
							{
								"t": "cho",
								"s": "ins"
							},
							{
								"t": " lý do. Chỉ có thứ đứng ra làm điều kiện, thứ được hứa trước và được đổi lấy, mới làm việc đó."
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn. Vốn ban đầu chúng thích vẽ và vẽ cũng chỉ vì thích, rồi khi vào thí nghiệm, không ai bắt chúng vẽ, không ai phạt, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, chúng ít vẽ dần đi. Điều này cũng khá giống chúng ta, ban đầu vốn thích làm cái gì đó bởi vì lý do tự thân bên trong chúng hoặc bên trong chúng ta, nhưng rồi có những lý do khác bên ngoài xuất hiện, rồi thay thế vị trí đó, cụ thể với mình là **code**, từ đầu mình thích code vì chính nó, vì sự tò mò cá nhân, vì cảm giác tự tạo ra cái gì đó của riêng mình. Nhưng rồi vào môi trường chuyên nghiệp, với KPI, đo lường, performance, khen thưởng,...vv, mình ít thích code dần. Có lẽ có một \"lời hứa\" nào đó đã thế chỗ cho lý do nội tại bên trong mình.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bạn hãy thử nhớ lại lần gần nhất bạn làm một việc gì đó chỉ vì chính nó hoặc chính bản thân bạn, có thể là đọc sách, học đàn, học vẽ, học võ, học bơi, leo núi,...vv.",
								"s": "ins"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Mình nghĩ về nhóm thứ nhất nhiều hơn mình muốn. Không ai bắt chúng vẽ, không ai phạt chúng, người lớn chỉ đưa ra một đề nghị nghe rất tử tế và chúng đồng ý. Rồi hai tuần sau, hộp bút màu nằm đó, và chúng đi qua.",
								"s": "del"
							}
						]
					},
					{
						"kind": "p",
						"segs": [
							{
								"t": "Bây giờ thử nhớ lại lần gần nhất bạn nói với chính mình rằng viết xong cái này thì sẽ có người đọc, chạy đủ tháng này thì sẽ đạt mục tiêu. Câu đó được nói ra trước hay sau khi bạn bắt đầu.",
								"s": "del"
							}
						]
					}
				]
			}
		]
	}
};
