/**
 * The open drafts, as git remembers them.
 *
 * GENERATED by `node scripts/drafts.mjs` — do not edit. The author's words in
 * here (a revision's note, its section states) come from the frontmatter of the
 * commit that saved it; everything else is computed.
 *
 * Plain `.js` for the same reason as `glossary.data.js`: the types live next
 * door in `drafts.ts`, which re-exports this, and JSDoc keeps checking.
 *
 * @type {import('./drafts').Drafts}
 */
export const DRAFTS = {};
